<?php

require_once(drupal_get_path('module', 'ms_crm') . '/includes/ms_crm.inc');

function ms_crm_cron() {
  // TODO: Remove test structures so that we always download the file.
  // TODO: Test for failure, don't update if the response fails
  // TODO: Make sure we only run once a day
  if (!is_file('response.xml')) {
    $service = new MSCrmIFD();

    $service->usr = variable_get('ms_crm_username', '');
    $service->pwd = variable_get('ms_crm_password', '');
    $service->domain = variable_get('ms_crm_domain', '');
    $service->org = variable_get('ms_crm_organization', '');
    $service->crmHost = variable_get('ms_crm_host', '');
    $service->crmProto = variable_get('ms_crm_proto', '');
    $service->crmService = variable_get('ms_crm_path', '');
    $service->crmDisco = variable_get('ms_crm_disco', '');

    // login into service      
    $service->getAccess();

    // Get the FetchXML from the database and entity encode it so we can push it
    // into the request XML code. 
    $fetchxml = htmlentities(variable_get('ms_crm_fetchxml', ''));

    // Prepare some request, put into request auth header
    $request = '<?xml version="1.0" encoding="utf-8"?>
      <soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
       ' . $service->getAuthHeader() . '
        <soap:Body>
            <Fetch xmlns="http://schemas.microsoft.com/crm/2007/WebServices">
                <fetchXml>' . $fetchxml . '</fetchXml>
            </Fetch>
        </soap:Body>
      </soap:Envelope>';

    // Get response
    $response = $service->request($request, 'http://schemas.microsoft.com/crm/2007/WebServices/Fetch');

    // TODO: This should not be saved this way, we should save from SimpleXMLElement
    // or not save at all
    $dom = new DOMDocument();
    $dom->loadXML(html_entity_decode($response));
    $dom->formatOutput = true;
    $xml = $dom->saveXML();
    $fp = fopen('response.xml', 'w');
    fwrite($fp, $xml);
  }
  $xml = new SimpleXMLElement(readfile('response.xml'));
}

/**
 * Implementation of hook_menu().
 */
function ms_crm_menu() {
  $items['admin/settings/ms-crm'] = array(
    'title' => 'MS Dynamics',
    'description' => 'Login and location settings for the crm integration',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ms_crm_admin_settings'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

/**
 * Settings for CRM integration
 */
function ms_crm_admin_settings() {
  $form = array();
  
  $form['ms_crm_username'] = array(
    '#title' => t('Username'),
    '#description' => t(''),
    '#type' => 'textfield',
    '#default_value' => variable_get('ms_crm_username', ''),
  );
  $form['ms_crm_password'] = array(
    '#title' => t('Password'),
    '#description' => t(''),
    '#type' => 'textfield',
    '#default_value' => variable_get('ms_crm_password', ''),
  );
  $form['ms_crm_domain'] = array(
    '#title' => t('AD Domain'),
    '#description' => t('AD Domain is the bit of the username before the \. For example this AD user\'s domain would be office: office\vosechu'),
    '#type' => 'textfield',
    '#default_value' => variable_get('ms_crm_domain', ''),
  );
  $form['ms_crm_organization'] = array(
    '#title' => t('Organization'),
    '#description' => t(''),
    '#type' => 'textfield',
    '#default_value' => variable_get('ms_crm_organization', ''),
  );
  $form['ms_crm_host'] = array(
    '#title' => t('Host'),
    '#description' => t('Hostname without http/https before it. Do not include the path in this string.'),
    '#type' => 'textfield',
    '#default_value' => variable_get('ms_crm_host', ''),
  );
  $form['ms_crm_proto'] = array(
    '#title' => t('Protocol'),
    '#description' => t('Usually http or https'),
    '#type' => 'textfield',
    '#default_value' => variable_get('ms_crm_proto', ''),
  );
  $form['ms_crm_path'] = array(
    '#title' => t('Service Path'),
    '#description' => t('Path to the Service asmx.'),
    '#default_value' => variable_get('ms_crm_path', '/MSCrmServices/2007/MSCrmServices/2007/CrmService.asmx'),
    '#type' => 'textfield',
  );
  $form['ms_crm_disco'] = array(
    '#title' => t('Discovery Path'),
    '#description' => t('Path to the Discovery asmx.'),
    '#default_value' => variable_get('ms_crm_disco', '/MSCRMServices/2007/SPLA/CrmDiscoveryService.asmx'),
    '#type' => 'textfield',
  );
  $form['ms_crm_fetchxml'] = array(
    '#title' => t('FetchXML Statement'),
    '#default_value' => variable_get('ms_crm_fetchxml', ''),
    '#type' => 'textarea',
  );
  
  return(system_settings_form($form));
}