<?php

require_once(drupal_get_path('module', 'ms_crm') . '/includes/ms_crm.inc');

function ms_crm_cron() {
  // TODO: Test for failure, don't update if the response fails
  // TODO: Make sure we only run once a day
  // TODO: Add module invokes to allow people to edit what happens with the 
  // data after we pull it down.
  $service = new MSCrmIFD();

  $service->usr = variable_get('ms_crm_username', '');
  $service->pwd = variable_get('ms_crm_password', '');
  $service->domain = variable_get('ms_crm_domain', '');
  $service->org = variable_get('ms_crm_organization', '');
  $service->crmHost = variable_get('ms_crm_host', '');
  $service->crmProto = variable_get('ms_crm_proto', '');
  $service->crmService = variable_get('ms_crm_path', '');
  $service->crmDisco = variable_get('ms_crm_disco', '');

  try {
    // login into service      
    $service->getAccess();
  }
  catch (Exception $e) {
    watchdog('ms_crm', 'Failed to connect to authentication service (' . $e . ')', array(), WATCHDOG_ERROR);
    return false;
  }

  // Get the FetchXML from the database and entity encode it so we can push it
  // into the request XML code. 
  $fetchxml = htmlentities(variable_get('ms_crm_fetchxml', ''));

  // Prepare some request, put into request auth header
  $request = '<?xml version="1.0" encoding="utf-8"?>
    <soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
     ' . $service->getAuthHeader() . '
      <soap:Body>
          <Fetch xmlns="http://schemas.microsoft.com/crm/2007/WebServices">
              <fetchXml>' . $fetchxml . '</fetchXml>
          </Fetch>
      </soap:Body>
    </soap:Envelope>';

  try {
    // Get response
    $response = $service->request($request, 'http://schemas.microsoft.com/crm/2007/WebServices/Fetch');

    // Create the xml object from the response
    $xml = new SimpleXMLElement(html_entity_decode($response));
  }
  catch (Exception $e) {
    watchdog('ms_crm', 'Failed to download new data (' . $e . ')', array(), WATCHDOG_ERROR);
    return false;
  }
  
  $results = $xml->xpath('/soap:Envelope/soap:Body');
  $results = $results[0]->FetchResponse->FetchResult->resultset->result;

  foreach($results as $result) {
    if ($nid = ms_crm_load((string) $result->accountid)) {
      $node = node_load($nid);
      foreach ($result as $key => $attr) {
        // Check for changes in the node. If there are any just rebuild the whole node.
        $dirty = FALSE;
        switch ($key) {
          case 'accountid': 
          case 'accountclassificationcode':
            break;
          case 'name':
            $dirty = ((string) $result->name != $node->title) ? TRUE : FALSE;
            break;
          case 'address1_line1':
            $dirty = ((string) $result->address1_line1 != $node->location['street']) ? TRUE : FALSE;
            break;
          case 'address1_line2':
            $dirty = ((string) $result->address1_line2 != $node->location['additional']) ? TRUE : FALSE;
            break;
          case 'address1_city':
            $dirty = ((string) $result->address1_city != $node->location['city']) ? TRUE : FALSE;
            break;
          case 'address1_stateorprovince':
            if ((string) $result->address1_stateorprovince != $node->location['province']) {
              // It's entirely possible that someone has put something in the state
              // field for a country that has no states. This will always end with
              // location failing to write that to the database so this will always
              // be dirty unless we check for it.
              $provinces = location_get_provinces($node->location['country']);
              if (count($provinces) != 0) {
                $dirty = TRUE;
              }
            }
            break;
          case 'address1_postalcode':
            $dirty = ((string) $result->address1_postalcode != $node->location['postal_code']) ? TRUE : FALSE;
            break;
          case 'address1_country':
            $r_country = (string) $result->address1_country;
            $r_country = ms_crm_misspellings(ucwords(strtolower($r_country)));
            $dirty = ($r_country != $node->location['country_name']) ? TRUE : FALSE;
            break;
          case 'telephone1':
            $dirty = ((string) $result->telephone1 != $node->location['phone']) ? TRUE : FALSE;
            break;
          case 'websiteurl':
            $dirty = ((string) $result->websiteurl != $node->field_url[0]['value']) ? TRUE : FALSE;
            break;
          case 'accountcategorycode':
            $term = array_shift($node->taxonomy);
            $dirty = ((string) $result->accountcategorycode['name'] != $term->name) ? TRUE : FALSE;
            break;
        }
        // If any attribute is different just update the whole thing with new values
        if ($dirty) {
          break 1; // Break out of the loop as soon as we find an attribute that's dirty
        }
      }
      if ($dirty) {
        $statuses['updated']++;
        $node = ms_crm_update($node, $result);
      }
      else {
        $statuses['not_changed']++;
      }
    }
    else {
      $statuses['created']++;
      $node = ms_crm_create($result);
    }
    $statuses['total']++;
  }
  
  echo " Total: " . $statuses['total'] .
       " Created: " . $statuses['created'] . 
       " Updated: " . $statuses['updated'] .
       " Not Changed: " . $statuses['not_changed'] . PHP_EOL;
}

/**
 * Load up an account by account_id returned by the CRM system. Returns the nid 
 * of a node with that account_id.
 */
function ms_crm_load($account_id) {
  list($table, $column) = helper_cck_field_sql('field_account_id');
  return db_result(db_query('SELECT nid FROM {%s} WHERE %s = "%s"', $table, $column, $account_id));
}

/**
 * Create a new reseller object based on the $result SimpleXMLElement passed in.
 * This will almost certainly only be called from ms_crm_cron.
 * the SimpleXMLElement should be created from a snippet like this:
 * <code>
 * <?xml version="1.0" encoding="utf-8"?>
 * <soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
 * <soap:Body>
 *  <FetchResponse xmlns="http://schemas.microsoft.com/crm/2007/WebServices">
 *    <FetchResult>
 *      <resultset morerecords="0" paging-cookie="&lt;cookie page=&quot;1&quot;&gt;&lt;accountid last=&quot;{8FA37981-2119-DE11-AD3A-0015C5FDF4E6}&quot; first=&quot;{7AA1FC5A-697E-DF11-889C-0015C5FD522D}&quot; /&gt;&lt;/cookie&gt;">
 *        <result>
 *          <name>Terrifico LLC</name>
 *          <address1_line1>S Terrific Street </address1_line1>
 *          <address1_line2>Suite 10</address1_line2>
 *          <address1_postalcode>13602</address1_postalcode>
 *          <address1_city>Watertown</address1_city>
 *          <address1_stateorprovince>NY</address1_stateorprovince>
 *          <websiteurl>http://www.terrifico.com</websiteurl>
 *          <telephone1>123-456-7890</telephone1>
 *          <accountcategorycode name="PC Reseller" formattedvalue="200002">200002</accountcategorycode>
 *          <accountclassificationcode name="United States" formattedvalue="200002">200002</accountclassificationcode>
 *          <accountid>{C1A406DC-39A9-DF11-88B7-0015C5FD522D}</accountid>
 *        </result>
 *      </resultset>
 *     </FetchResult>
 *   </FetchResponse>
 * </soap:Body>
 * <code>
 */
function ms_crm_create($result) {
  $node = new stdClass();
  $node->type = 'reseller';
  $node->title = (string) $result->name;
  
  return ms_crm_build($node, $result);
}

/**
 * Update the reseller object
 * @see ms_crm_create
 */
function ms_crm_update($node, $result) {
  return ms_crm_build($node, $result);
}

/**
 * Build and save the reseller object.
 * @see ms_crm_create
 */
function ms_crm_build($node, $result) {
  // Create/Update a new location and associate it with the node
  $location = ms_crm_location_create($result);
  $node->locations[0] = $location;
  $node->location = $location;
  
  // Pull in the website url
  $node->field_url[0]['value'] = (string) $result->websiteurl;
  
  // Store the account id so we can check to see if this has been updated
  $node->field_account_id[0]['value'] = (string) $result->accountid;
  
  switch ($result->accountcategorycode['name']) {
    case 'PC Reseller':
      $term = taxonomy_get_term_by_name('PC Reseller');
      $node->taxonomy[$term[0]->tid] = $term[0];
      break;
    case 'AV Reseller':
      $term = taxonomy_get_term_by_name('AV Reseller');
      $node->taxonomy[$term[0]->tid] = $term[0];
      break;
  }
  
  node_save($node);
  
  return $node;
}

function ms_crm_location_create($result, $node = NULL) {
  // Translate the country name into country code
  $country_list = location_get_iso3166_list();
  $r_country = (string) $result->address1_country;
  $r_country = ms_crm_misspellings(ucwords(strtolower($r_country)));
  $country_code = array_search($r_country, $country_list);
  if (!$country_code) {
    if (location_province_code('us', (string) $result->address1_stateorprovince) != '') {
      $country_code = 'us';
    }
  }
  if (!$country_code) {
    print("Invalid country: " . $r_country . PHP_EOL);
  }
  
  // Create a location object out of the location details and save it
  $loc = $node ? $node->location : array();
  $loc['street'] = (string) $result->address1_line1;
  $loc['additional'] = (string) $result->address1_line2;
  $loc['city'] = (string) $result->address1_city;
  $loc['province'] = (string) strtoupper($result->address1_stateorprovince);
  $loc['postal_code'] = (string) $result->address1_postalcode;
  $loc['country'] = $country_code;
  $loc['phone'] = (string) $result->telephone1;

  // Create the actual location object and add it to the CCK attached location field
  $lid = location_save($loc, TRUE, $node->locations[0]['lid']);
  $location = location_load_location($lid);
  
  return $location;
}

/**
 * There are a number of... regretable misspellings in the CRM database. We will
 * need a pretty solid way to deal with this but I don't think making an admin
 * interface is really necessary. 
 * This function merely maps between a misspelling and its actual country name as
 * listed by ISO3166. 
 */
function ms_crm_misspellings($country_name) {
  switch ($country_name) {
    case 'Columbia':
      return 'Colombia';
    case 'Usunited States':
    case 'Untied States':
    case 'Usa':
    case 'Us':
      return 'United States';
    case 'Ca':
      return 'Canada';
    case 'Korea':
      return 'South Korea';
    case 'Sg':
      return 'Singapore';
    case 'Uae':
      return 'United Arab Emirates';
    case 'Mt':
      return 'Malta';
    case 'Ar':
      return 'Argentina';
    case 'Cayman Islands, Bwi':
      return 'Cayman Islands';
    case 'St Lucia':
      return 'Saint Lucia';
    case 'Trinidad':
      return 'Trinidad and Tobago';
    default:
      return $country_name;
  }
}

/**
 * Implementation of hook_menu().
 */
function ms_crm_menu() {
  $items['admin/settings/ms-crm'] = array(
    'title' => 'MS Dynamics',
    'description' => 'Login and location settings for the crm integration',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ms_crm_admin_settings'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

/**
 * Settings for CRM integration
 */
function ms_crm_admin_settings() {
  $form = array();
  
  $form['ms_crm_username'] = array(
    '#title' => t('Username'),
    '#description' => t(''),
    '#type' => 'textfield',
    '#default_value' => variable_get('ms_crm_username', ''),
  );
  $form['ms_crm_password'] = array(
    '#title' => t('Password'),
    '#description' => t(''),
    '#type' => 'textfield',
    '#default_value' => variable_get('ms_crm_password', ''),
  );
  $form['ms_crm_domain'] = array(
    '#title' => t('AD Domain'),
    '#description' => t('AD Domain is the bit of the username before the \. For example this AD user\'s domain would be office: office\vosechu'),
    '#type' => 'textfield',
    '#default_value' => variable_get('ms_crm_domain', ''),
  );
  $form['ms_crm_organization'] = array(
    '#title' => t('Organization'),
    '#description' => t(''),
    '#type' => 'textfield',
    '#default_value' => variable_get('ms_crm_organization', ''),
  );
  $form['ms_crm_host'] = array(
    '#title' => t('Host'),
    '#description' => t('Hostname without http/https before it. Do not include the path in this string.'),
    '#type' => 'textfield',
    '#default_value' => variable_get('ms_crm_host', ''),
  );
  $form['ms_crm_proto'] = array(
    '#title' => t('Protocol'),
    '#description' => t('Usually http or https'),
    '#type' => 'textfield',
    '#default_value' => variable_get('ms_crm_proto', ''),
  );
  $form['ms_crm_path'] = array(
    '#title' => t('Service Path'),
    '#description' => t('Path to the Service asmx.'),
    '#default_value' => variable_get('ms_crm_path', '/MSCrmServices/2007/MSCrmServices/2007/CrmService.asmx'),
    '#type' => 'textfield',
  );
  $form['ms_crm_disco'] = array(
    '#title' => t('Discovery Path'),
    '#description' => t('Path to the Discovery asmx.'),
    '#default_value' => variable_get('ms_crm_disco', '/MSCRMServices/2007/SPLA/CrmDiscoveryService.asmx'),
    '#type' => 'textfield',
  );
  $form['ms_crm_fetchxml'] = array(
    '#title' => t('FetchXML Statement'),
    '#default_value' => variable_get('ms_crm_fetchxml', ''),
    '#type' => 'textarea',
  );
  
  return(system_settings_form($form));
}

/**
 * function to get the TABLE or COLUMN for a CCK FIELD
 * method adapted from http://drewish.com/content/2010/06/correctly_accessing_cck_fields_in_sql_queries
 * and taken from http://benbuckman.net/tech/10/08/drupal-using-cck-fieldss-inconsistent-tables-custom-queries
 *
 * @param $field_name
 * @param $type 'table' or 'column'
 *
 * to get both table and column, run function twice with each $type
 */
function helper_cck_field_sql($field_name, $type='table') {
  $field = content_fields($field_name);
  $db_info = content_database_info($field);
 
  if (isset($db_info['table']) && isset($db_info['columns']['value']['column'])) {
    return array($db_info['table'], $db_info['columns']['value']['column']);
  }
  return NULL;
}